apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: client-service
  namespace: garage
spec:
  hosts:
    - client-service.garage.svc.cluster.local
  http:
    - route:
        - destination:
            host: client-service
            subset: v1
          weight: 90
        - destination:
            host: client-service
            subset: v2
          weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: client-service
  namespace: garage
spec:
  host: client-service
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
